### ISSUE TITLE
Error talking to auth server after some time

### ISSUE THREAD

**Issue by TakeMeNL** [PufferPanel/pufferd#41]
```
[21:18:22] [ERROR] Error talking to auth server
Post https://<SNIP>/oauth2/token/info: dial tcp: lookup <SNIP> on 208.67.220.220:53: dial udp 208.67.220.220:53: socket: too many open files
[21:18:22] [ERROR] Error handling route
interface conversion: interface is nil, not []string
goroutine 15606 [running]:
runtime/debug.Stack(0xc42236db00, 0x884920, 0xc42236d980)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
github.com/pufferpanel/pufferd/httphandlers.Recovery.func1.1(0xc425060000)
        /srv/build/pufferd/src/github.com/pufferpanel/pufferd/httphandlers/errorlogging.go:15 +0x18c
panic(0x884920, 0xc42236d980)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/pufferpanel/pufferd/httphandlers.OAuth2Handler.func1(0xc425060000)
        /srv/build/pufferd/src/github.com/pufferpanel/pufferd/httphandlers/oauth2.go:79 +0x8d5
github.com/gin-gonic/gin.(*Context).Next(0xc425060000)
        /srv/build/pufferd/src/github.com/gin-gonic/gin/context.go:97 +0x5a
github.com/pufferpanel/pufferd/httphandlers.Recovery.func1(0xc425060000)
        /srv/build/pufferd/src/github.com/pufferpanel/pufferd/httphandlers/errorlogging.go:19 +0x51
github.com/gin-gonic/gin.(*Context).Next(0xc425060000)
        /srv/build/pufferd/src/github.com/gin-gonic/gin/context.go:97 +0x5a
github.com/gin-gonic/gin.RecoveryWithWriter.func1(0xc425060000)
        /srv/build/pufferd/src/github.com/gin-gonic/gin/recovery.go:45 +0x5a
github.com/gin-gonic/gin.(*Context).Next(0xc425060000)
        /srv/build/pufferd/src/github.com/gin-gonic/gin/context.go:97 +0x5a
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest(0xc4202120e0, 0xc425060000)
        /srv/build/pufferd/src/github.com/gin-gonic/gin/gin.go:284 +0x64e
github.com/gin-gonic/gin.(*Engine).ServeHTTP(0xc4202120e0, 0xb1cd20, 0xc4216c2c30, 0xc4244b1c20)
        /srv/build/pufferd/src/github.com/gin-gonic/gin/gin.go:265 +0x130
github.com/braintree/manners.(*gracefulHandler).ServeHTTP(0xc42010efc0, 0xb1cd20, 0xc4216c2c30, 0xc4244b1c20)
        /srv/build/pufferd/src/github.com/braintree/manners/server.go:277 +0x8f
net/http.serverHandler.ServeHTTP(0xc42012e500, 0xb1cd20, 0xc4216c2c30, 0xc4244b1c20)
        /usr/local/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc422eab580, 0xb1d5a0, 0xc4221b0f80)
        /usr/local/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2293 +0x44d
```

**Comment by LordRalex** [comment]
https://github.com/PufferPanel/pufferd/commit/5074e03a1da6405613eb32f90690ae62bf531da2
